version: "3.8"

# Template Docker Compose file with additional services
# Copy and modify this file for your specific needs

services:
  # Uptime Kuma - Monitoring
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - uptimekuma_data:/app/data
    ports:
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`uptime.localhost`)"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-myapp}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-myapp}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uptimekuma_data:
  postgres_data:

networks:
  traefik_network:
    external: true
