version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8888:8080"  # Traefik dashboard
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/dynamic.yml:/dynamic.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/logs:/logs
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  traefik_network:
    external: true